name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Build
      run: |
        cd 'Movies Versions'
        dotnet publish -o app
        cd app
        
     - name: GitHub Action for Heroku
       uses: actions/heroku@1.0.0
       env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       run: |
         container:login
         container:push -a moviesversion web
         container:release -a moviesversion web

        
