name: CI

on: [push]

jobs:
  build:

  runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
      with:
          dotnet-version: '2.2.103' # SDK Version to use.
    - name: Build
      run: |
        cd 'Movies Versions'
        dotnet publish -o app
        cd app
    

